export const LOGGED_USER_INFO_ACTION = 'LOGGED_USER_INFO_ACTION';
export const APPLICATION_DATA_ACTION = 'APPLICATION_DATA_ACTION';
export const APPROVE_APPLICATION_ACTION = 'APPROVE_APPLICATION_ACTION';


